version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "${APP_DOCKER_HOST_PORT}:80"
    volumes:
    - .:/var/www
    - ./docker/config/nginx:/etc/nginx/conf.d
    - ./docker/logs/nginx:/var/log/nginx
    links:
    - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    ports:
    - 9000:9000
    volumes:
    - .:/var/www
    - ./docker/config/php:/usr/local/etc/php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
    - database

  database:
    hostname: ${DB_HOST}
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_DOCKER_HOST_PORT}:5432"
    volumes:
      - ./docker/databases/postgres:/var/lib/postgresql/data
