version: "3.7"

services:

  nginx:
    image: nginx:latest
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./src:/var/www/project
    - ./config/nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    links:
    - php-fpm

  php-fpm:
    build:
      context: php-fpm
    ports:
    - 127.0.0.1:9000:9000
    volumes:
    - ./src:/var/www/project
    links:
    - db

  db:
    image: postgres:latest
    ports:
    - 127.0.0.1:5432:5432
    restart: always
    environment:
    - POSTGRES_HOST_AUTH_METHOD=md5
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=test
    - POSTGRES_DB=test
    volumes:
    - ./databases/postgres:/var/lib/postgresql/data
